config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  scope '(:locale)', :locale => /en|uk/ do # at the beginning

    devise_for :users

    # Creates set of REST routes
    resources :films do
      get 'search', on: :collection
    end

  end
  get '/:locale' => 'films#index'
  # Set root URL
  root :to => 'welcome#index'
end

app/models/film.rb
class Film < ActiveRecord::Base
  has_and_belongs_to_many :users

  validates :title, :category, :genres, :country, presence: true
  scope :joined, -> { joins(:users) }
  scope :user_films, -> (current_user_id) { joined.where(users: { id: current_user_id }) }
  scope :genres, -> (current_user_id, genre) { joined.where { (users.id == current_user_id ) & (genres =~ "%#{genre}%") } }
  scope :category, -> (current_user_id, value) { joined.where { (users.id == current_user_id) & (category == "#{value}") } }
  scope :tags, ->(current_user_id, tag) { joined.where { (users.id == current_user_id) & (tags =~ "%#{tag}%") } }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :films

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def self.default_url_options(options={})
    options.merge({ :locale => I18n.locale })
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController

  before_action :authenticate_user!
  before_filter :find_item, only: [:show, :edit, :update, :destroy]

  before_action :update_tags, only: [:index, :new, :search]
  after_action :update_tags, only: [:update]

  def index
    @user = current_user
    ## FIXME replace with scope user_films
    @films = Film.joins(:users).where(users: { id: current_user.id })
    @films = @films.genres(current_user.id, params[:genre]) if params[:genre]
    @films = @films.category(current_user.id, params[:category]) if params[:category]
    @films = @films.tags(current_user.id, params[:tag]) if params[:tag]
  end

  def show
    unless @film
      render text: 'Page not Found', status: 404
    end
  end

  def new
    @film = Film.new

    if params[:add_field] && !params[:add_field].empty?
      # Strip whitespaces for '+' to build correct GET request
      add_field = params[:add_field].tr(' ', '+')
      url = "http://#{Rails.env.production? ? 'brb' : 'fs'}.to/search.aspx?f=quick_search&search=#{add_field}&section=video"
      encoded_url = URI.encode(url)
      client = HTTPClient.new
      request = client.get(encoded_url)
      # Parse JSON response and delete records that don't belong to 'video' section
      @add_result = ActiveSupport::JSON.decode(request.body).delete_if { |hash| hash['section'] != 'video' }
      @add_result.map do |i|
        doc = Nokogiri::HTML(open("#{ 'http://fs.to' + i['link'] }"))
        itemprop_image = doc.xpath("//img[@itemprop='image']")
        itemprop_description = doc.xpath("/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[1]/div[1]/div/div[4]/span/p")

        # Get description
        i['description'] = itemprop_description.children.text

        # Get the link of original image poster through XPath
        if itemprop_image.empty?
          i['poster'] = '/assets/help.png'
        else
          i['poster'] = itemprop_image.attr('src').value
        end
      end
    elsif params[:add_field] && params[:add_field].empty?
      @add_result = ''
    else
      render 'new'
    end
  end

  def create
    @user = current_user

    @film = Film.new.tap do |f|
      f.image = params['poster']
      f.title = params['title']
      f.link = params['link']
      f.genres = params['genres']
      f.category = params['category']
      f.year = params['year']
      f.country = params['country']
      f.description = params['description']
    end

    doc = Nokogiri::HTML(open("#{ @film.link }"))

    original_title = if @film.category == 'Телепередачи'
                       doc.xpath('/html/body/div[1]/div/div[2]/div/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div/div').children.text
                     else
                       doc.xpath("//div[@itemprop='alternativeHeadline']").text
                     end

    @film.original_title = original_title

    if @film.save
      @user.films << @film
      redirect_to :back
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @film.tags = params[:tags]
    p 'params[:tags'  + params[:tags]
    p @film.tags
    p @film.save

    redirect_to  root_path
  end

  def search
    if params[:search_field] && !params[:search_field].empty?
      search_result = params[:search_field]
      user = current_user.id # => squeel workimg properly after this
      @search_result = Film.joins(:users).where { (users.id == user) & (title.matches "%#{search_result}%") }
    elsif params[:search_field] && params[:search_field].empty?
      @search_result = ''
    else
      render 'search'
    end
  end

  def destroy
    @film.destroy
    redirect_to films_path
  end

  private
  def allowed_params
    params.require(:film).permit(:title, :year, :genres, :rating)
  end

  def find_item
    @film = Film.find(params[:id])
  end

  def update_tags
    @uniq_tags = []
    arr = []
    Film.user_films(current_user.id).to_a.each {|i| arr << i.tags unless i.tags.nil? }

    p 'arr = ' + arr.to_s
    @uniq_tags = arr.join(', ').split(', ').uniq.reject(&:empty?)
    p @uniq_tags.to_s
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to controller: 'films', action: 'index'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_in_li_local(body, badge_num, hash, html_options = {})
    url = "/#{I18n.locale.to_s}/films?#{hash.keys[0].to_s}=#{hash.values[0].to_s}"
    active = "active" if current_page?(url)
    content_tag :li, class: active do
      link_to content_tag(:span, "#{badge_num.to_s}", class: 'badge pull-right') + body, url, html_options
    end
  end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/films/edit.html.erb
<!--<#%= render partial: 'partials/menu_bar' %>-->

<!--<div class="container">-->
  <!--<div class="row">-->

    <!--<div class="col-md-3">-->
    <!--<#%= render partial: 'partials/side_menu' %>-->
    <!--</div>-->
    <!--<div class="modal fade" id="showModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">-->
      <!--<div class="modal-dialog">-->
        <!--<div class="modal-content">-->
          <!--<div class="col-md-6">-->
          <!--<div class="center-block">-->
          <h1><%= @film.title %></h1>
          <%= form_for @film do |f| %>
              <%= render partial: 'partials/form', locals: { f: f } %>
              <%= f.submit 'Update film', class: 'btn btn-success' %>
          <% end %>
          <!--</div>-->
        <!--</div>-->
      <!--</div>-->
    <!--</div>-->
  <!--</div>-->


<!--</div>-->
<!--</div>-->

app/views/films/index.html.erb
<%= render partial: 'partials/menu_bar' %>

<div class="container">
  <div class="row">

    <div class="col-md-3">
      <%= render partial: 'partials/side_menu' %>
    </div>

    <div class="col-md-9">
      <div class="row">
        <% if @films.empty? %>
            <h1 align="center"> <%= t('.add_materials') %></h1>
        <% else %>
            <% @films.each_with_index do |film, index| %>
            <div class="col-md-4 col-sm-6 col-lg-3">
              <div class="text-center thumbnail">

                <img src="<%= film.image %>" alt="poster" class="round-pic"/>
                <%= link_to fa_icon('remove', class: 'fa-fw'), film, method: :delete, class: 'video-item-delete' %>

                <div class="poster-actions">
                  <div class="poster-actions-inner">
                    <%= link_to fa_icon('eye', class: 'fa-fw'), film.link, class: 'video-item-show' %>
                    <%= link_to fa_icon('edit', class: 'fa-fw'), '', class: 'video-item-edit', 'data-toggle' => 'modal', 'data-target' => '#showModal' + index.to_s %>
                  </div>
                </div>

              </div>

              <p class="text-center nice-height"> <%= film.title %> </p>
            </div>
            <%= render partial: 'partials/modal', locals: { edit_film: film, edit_index: index } %>
            <% end %>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/films/new.html.erb
<%= render partial: 'partials/menu_bar' %>

<div class="container">
  <div class="row">

    <div class="col-md-3">
      <%= render partial: 'partials/side_menu' %>
    </div>

    <div class="col-md-9">
      <div class="row">
        <%= form_tag(new_film_path, id: 'new-form', method: 'get') do %>
            <h3 align="center"> <%= t('.find_header') %> </h3>

            <div class="input-group">
              <%= text_field_tag('add_field', nil, class: 'form-control', id: 'new-input',  type: 'text', maxlength: 50, placeholder: t('.search_placeholder'), autofocus: true) %>
              <span class="input-group-btn">
                <button type="submit" class="btn btn-default"> <%= t('.search_button') %> </button>
              </span>
            </div>
        <% end %>

        <!-- FIXME make this work by ruby on rails stuff!-->
        <script>
            $(document).ready(function () {
                $('#new-form').on('input', function () {
                    var capitalized = $('#new-input').val();
                    if (capitalized.length === 0) return;
                    capitalized = capitalized[0].toUpperCase() + capitalized.substring(1);
                    $('#new-input').val(capitalized);
                })
            })
        </script>

      </div>
      <br/>

      <div class="row">
        <!--<img src="http://cs5.pikabu.ru/images/big_size_comm_an/2015-04_2/14283911539244.gif" style="display: none;" id="loading_image">-->
        <% if @add_result.nil? %>
            <!-- First time clicked on add button-->
        <% elsif @add_result.empty? %>
            <%= render partial: 'partials/no_results' %>
        <% else %>
            <% @add_result.each do |result| %>
                <div class="col-md-3 col-sm-6 col-lg-3 text-center">
                  <%= form_tag('/films', id: 'form', method: :post) do %>
                      <input type="hidden" value="<%= result['poster'] %>" name="poster"/>
                      <input type="hidden" value="<%= result['title'] %>" name="title"/>
                      <input type="hidden" value="<%= 'http://www.fs.to' + result['link'] %>" name="link"/>
                      <input type="hidden" value="<%= result['genres'].class == Array ? result['genres'].join(', ') : result['genres'] = '–' %>" name="genres"/>
                      <input type="hidden" value="<%= result['subsection'] %>" name="category"/>
                      <input type="hidden" value="<%= result['year'][0] %>" name="year"/>
                      <input type="hidden" value="<%= result['country'][0] %>" name="country"/>
                      <input type="hidden" value="<%= result['description'] %>" name="description"/>

                      <div class="video-add-height">
                        <div class="thumbnail">
                          <img src="<%= result['poster'] %>" alt="poster" class="round-pic"/>

                          <div class="poster-actions-add">
                            <%= link_to fa_icon('plus-square 3x', class: 'fa-fw'), '', class: 'video-add', onclick: "$(this).closest('form').submit()" %>
                          </div>
                        </div>

                        <h5 class="title-height"> <%= link_to result['title'], 'http://www.fs.to' + result['link'] %> </h5>

                        <p class="p-default-height"> <%= t('modal.category') + result['subsection'] %> </p>

                        <p class="p-genres-height">
                          <%= t('modal.genres') + (result['genres'].class == Array ? result['genres'].join(', ') : result['genres'] = '–') %> </p>

                        <p class="p-default-height"> <%= t('modal.year') + result['year'][0].to_s %> </p>

                        <p class="p-default-height"> <%= t('modal.country') + result['country'][0] %> </p>
                      </div>
                  <% end %>
                </div>
            <% end %>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/films/search.html.erb
<%= render partial: 'partials/menu_bar' %>

<div class="container">
  <div class="row">

    <div class="col-md-3">
      <%= render partial: 'partials/side_menu' %>
    </div>

    <div class="col-md-9">
      <div class="row">

        <%= form_tag(search_films_path, id: 'search-form', method: 'get') do %>
            <h3 align="center"><%= t('.search_label') %></h3>

            <div class="input-group">
              <%= text_field_tag('search_field', nil, class: 'form-control', id: 'search-input', type: 'text', maxlength: 50, placeholder: t('films.new.search_placeholder'), autofocus: true) %>
              <span class="input-group-btn">
                <button type="submit" class="btn btn-default"><%= t('films.new.search_button') %></button>
              </span>
            </div>
        <% end %>

        <!-- FIXME make this work by ruby on rails stuff!-->
        <script>
            $(document).ready(function () {
                $('#search-form').on('input', function () {
                    var capitalized = $('#search-input').val();
                    if (capitalized.length === 0) return;
                    capitalized = capitalized[0].toUpperCase() + capitalized.substring(1);
                    $('#search-input').val(capitalized);
                })
            })
        </script>

      </div>
      <br/>

      <div class="row">
        <% if @search_result.nil? %>
        <% elsif @search_result.empty? %>
            <%= render partial: 'partials/no_results' %>
        <% else %>
            <h3 align="center"><%= t('.found_records', number: @search_result.count) %></h3>
            <% @search_result.each_with_index do |item, index| %>
                <div class="col-md-3 col-sm-6">
                  <div class="col-md-4 col-sm-6 col-lg-3">
                    <div class="text-center thumbnail">

                      <img src="<%= item.image %>" alt="poster" class="round-pic"/>
                      <%= link_to fa_icon('remove', class: 'fa-fw'), item, method: :delete, class: 'video-item-delete' %>

                      <div class="poster-actions">
                        <div class="poster-actions-inner">
                          <%= link_to fa_icon('eye', class: 'fa-fw'), item.link, class: 'video-item-show' %>
                          <%= link_to fa_icon('edit', class: 'fa-fw'), '', class: 'video-item-edit', 'data-toggle' => 'modal', 'data-target' => '#showModal' + index.to_s %>
                        </div>
                      </div>

                    </div>
                  </div>
                  <%= render partial: 'partials/modal', locals: { edit_film: item, edit_index: index } %>
                </div>
            <% end %>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/films/show.html.erb
<!--<#%= render partial: 'partials/menu_bar' %>-->

<h1><%= @film.title %></h1>

<%= link_to 'Back', films_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VideoDepot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta content="width=device-width, initial-scale=1" name="viewport">
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/partials/_bottom_bar.html.erb
<footer class="nav navbar-default navbar-bottom">
  <div class="container">
    <div class="row">
      <div class="center-block">
        <%= link_to 'VideoDepot', root_url %> | Maksym Tymoshyk
      </div>
    </div>
</div>
</footer>

app/views/partials/_form.html.erb
<div class="input-group">
    <%= f.text_field :title, class: 'form-control', placeholder: 'Name' %>
</div>
<br/>
<div class="input-group">
    <%= f.text_field :year, class: 'form-control', placeholder: 'Year' %>
</div>
<br/>
<div class="input-group">
    <%= f.text_field :rating, class: 'form-control', placeholder: 'Rating' %>
</div>
<br/>
<div class="input-group">
  <%= f.text_field :genres, class: 'form-control', placeholder: 'Genre' %>
</div>
<br/>

app/views/partials/_menu_bar.html.erb
<nav class="navbar navbar-default navbar-fixed-top top-menu">
  <div class="container">

    <div class="navbar-header">
      <!--<a class="navbar-brand" href="/">-->
        <%= link_to root_path, class: 'navbar-brand' do %>
            <img alt="Brand" src="/assets/logo.png" class="brand-class">
        <% end %>
      <!--</a>-->
    </div>

    <div class="collapse navbar-collapse ">
      <ul class="nav navbar-nav navbar-right icon-link">
        <li> <%= link_to fa_icon('plus 2x', class: 'fa-fw'), new_film_path %> </li>
        <li> <%= link_to fa_icon('search 2x', class: 'fa-fw'), search_films_path %> </li>
        <li>
          <%= link_to '#', class: 'user', data: { toggle: 'dropdown' }, role: 'button' do %>
              <%= current_user.email %>
              <%= fa_icon('caret-square-o-down', class: 'fa-fw') %>
          <% end %>
          <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                  <%= fa_icon('pencil', class: 'fa-fw') %>
                  <%= t('menu_bar.account_settings.edit_account') %>
              <% end %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to destroy_user_session_path, :method => :delete do %>
                  <%= fa_icon('sign-out', class: 'fa-fw') %>
                  <%= t('menu_bar.account_settings.sign_out') %>
              <% end %>
            </li>
          </ul>
        </li>
        <li class="locales">
          <%= link_to params.merge(locale: 'en') do %>
              <i class="famfamfam-flag-gb"></i> UK
          <% end %>
        </li>
        <li class="locales">
          <%= link_to params.merge(locale: 'uk') do %>
              <i class="famfamfam-flag-ua"></i> UA
          <% end %>
        </li>
      </ul>
    </div>

  </div>
</nav>

app/views/partials/_modal.html.erb
<!-- Modal start -->
<div class="modal fade" id="showModal<%= edit_index %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for edit_film do |f| %>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel" align="center"> <%= edit_film.title %>
              / <%= edit_film.original_title %> </h4>
          </div>
          <div class="modal-body">
            <div class="container">
              <div class="row">
                <div class="col-md-2">
                  <img src="<%= edit_film.image %>"/>
                </div>
                <div class="col-md-4">
                  <div class="row">
                    <div class="col-md-10">
                      <p class="modal-text"> <%= t('modal.category') + edit_film.category %> </p>

                      <p class="modal-text"> <%= t('modal.genres') + edit_film.genres %> </p>

                      <p class="modal-text"> <%= t('modal.country') + edit_film.country %> </p>

                      <p class="modal-text"> <%= t('modal.year') + edit_film.year.to_s %> </p>

                      <p class="modal-text"> <%= t('modal.description') + edit_film.description %> </p>

                      <p class="modal-text"> <%= t('modal.tags') %> <%= text_field_tag('tags', edit_film.tags, placeholder: t('modal.type_tags'), class: 'tokenize') %>
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <%= f.submit(t('modal.save_changes'), class: 'btn btn-success') %>
            <%= link_to t('modal.delete_record'), edit_film, method: :delete, class: 'btn btn-danger' %>
          </div>
      <% end %>
    </div>
  </div>
</div>
<script>
    $('input.tokenize').tokenfield();
</script>
<!-- Modal end -->

app/views/partials/_no_results.erb
<div class="text-center">
  <h1><%= t('no_results.no_results_header') %></h1>
  <h4><%= t('no_results.no_results_paragraph') %></h4>
</div>

app/views/partials/_side_menu.html.erb
<script>
    $(function () {
        $("#accordion").accordion({
            active: <% if params.has_key?(:category) %>   0 // category section
            <% elsif params.has_key?(:genre) %>   1 // genres section
                    <% elsif params.has_key?(:tag)  %>   2 // tags section
            <% else %>                            0 // by default using category behaviour
            <% end %>
        });
    });
</script>

<!-- sidebar menu-->
<h3 id="my_list_header"><%= link_to t('films.side_menu.my_list'), root_path, name: 'film_counter', data: { toggle: 'tooltip' }, title: "#{Film.user_films(current_user.id).count.to_s}" %></h3>

<script>
    $('a[name=film_counter]').tooltip({
        /*or use any other selector, class, ID*/
        placement: "right",
        trigger: "hover"
    });
</script>

<hr/>

<div id="accordion">
  <h3><%= t('films.side_menu.categories') %></h3>

  <div>
    <ul class="nav nav-pills nav-stacked" id="sidebar-category">
      <%= link_to_in_li_local t('films.side_menu.films'), Film.category(current_user.id, 'Фильмы').count, category: 'Фильмы', id: 'films_link' %>
      <%= link_to_in_li_local t('films.side_menu.tv_series'), Film.category(current_user.id, 'Сериалы').count, category: 'Сериалы', id: 'series_link' %>
      <%= link_to_in_li_local t('films.side_menu.cartoons'), Film.category(current_user.id, 'Мультфильмы').count, category: 'Мультфильмы', id: 'cartoons_link' %>
      <%= link_to_in_li_local t('films.side_menu.cartoon_series'), Film.category(current_user.id, 'Мультсериалы').count, category: 'Мультсериалы', id: 'cartoon_series_link' %>
      <%= link_to_in_li_local t('films.side_menu.shows'), Film.category(current_user.id, 'Телепередачи').count, category: 'Телепередачи', id: 'shows_link' %>
      <%= link_to_in_li_local t('films.side_menu.concerts'), Film.category(current_user.id, 'Концерты').count, category: 'Концерты', id: 'concerts_link' %>
      <%= link_to_in_li_local t('films.side_menu.clips'), Film.category(current_user.id, 'Клипы').count, category: 'Клипы', id: 'clips_link' %>
    </ul>
  </div>

  <h3><%= t('films.side_menu.genres') %></h3>

  <div>
    <ul class="nav nav-pills nav-stacked" id="sidebar-menu">
      <%= link_to_in_li_local t('films.side_menu.anime'), Film.genres(current_user.id, 'аниме').count, genre: 'аниме', id: 'anime_link' %>
      <%= link_to_in_li_local t('films.side_menu.action'), Film.genres(current_user.id, 'боевик').count, genre: 'боевик', id: 'action_movie_link' %>
      <%= link_to_in_li_local t('films.side_menu.detective'), Film.genres(current_user.id, 'детектив').count, genre: 'детектив', id: 'detective_link' %>
      <%= link_to_in_li_local t('films.side_menu.documentary'), Film.genres(current_user.id, 'документальный').count, genre: 'документальный', id: 'documentary_link' %>
      <%= link_to_in_li_local t('films.side_menu.drama'), Film.genres(current_user.id, 'драма').count, genre: 'драма', id: 'drama_link' %>
      <%= link_to_in_li_local t('films.side_menu.comedy'), Film.genres(current_user.id, 'комедия').count, genre: 'комедия', id: 'comedy_link' %>
      <%= link_to_in_li_local t('films.side_menu.adventure'), Film.genres(current_user.id, 'приключения').count, genre: 'приключения', id: 'adventure_link' %>
      <%= link_to_in_li_local t('films.side_menu.family'), Film.genres(current_user.id, 'семейный').count, genre: 'семейный', id: 'family_link' %>
      <%= link_to_in_li_local t('films.side_menu.thriller'), Film.genres(current_user.id, 'триллер').count, genre: 'триллер', id: 'thriller_link' %>
      <%= link_to_in_li_local t('films.side_menu.horror'), Film.genres(current_user.id, 'ужасы').count, genre: 'ужасы', id: 'horror_link' %>
      <%= link_to_in_li_local t('films.side_menu.fiction'), Film.genres(current_user.id, 'фантастика').count, genre: 'фантастика', id: 'fiction_link' %>
      <%= link_to_in_li_local t('films.side_menu.fantasy'), Film.genres(current_user.id, 'фэнтези').count, genre: 'фэнтези', id: 'fantasy_link' %>
      <%= link_to_in_li_local t('films.side_menu.erotica'), Film.genres(current_user.id, 'эротика').count, genre: 'эротика', id: 'erotica_link' %>
    </ul>
  </div>

  <h3><%= t('films.side_menu.tags') %></h3>

  <div>
    <ul class="nav nav-pills nav-stacked">
      <% unless @uniq_tags.nil? %>
          <% @uniq_tags.each do |t| %>
              <p> <%= link_to_in_li_local t, Film.tags(current_user.id, t).count, tag: t %> </p>
          <% end %>
      <% end %>
    </ul>
  </div>

</div> <!-- accordion -->
<!-- sidebar menu end-->

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to t('users.sessions.new.legend_label'), new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to t('users.registrations.new.legend_label'), new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <!-- TODO make me work!-->
  <!--<#%= link_to t('users.registrations.new.forgot_password'), new_password_path(resource_name) %><br />-->
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<body class="welcome-body">
<div class="welcome-locales">
  <%= link_to params.merge(locale: 'en') do %>
      <i class="famfamfam-flag-gb"></i> UK
  <% end %>
  <%= link_to params.merge(locale: 'uk') do %>
      <i class="famfamfam-flag-ua"></i> UA
  <% end %>
</div>
<div class="container site-wrapper">
  <div class="jumbotron">
    <div class="text-center inner">
      <img src="/assets/logo-big.png"/>

      <h1 class="cover-heading"> <%= t('.slogan') %></h1>

      <p class="lead"> <%= t('.short_decription') %> </p>

      <p class="lead">
        <%= link_to t('.button'), { controller: 'films', action: 'index' }, class: 'btn btn-lg btn-default' %>
      </p>

      <!-- Just to remember-->
      <!--<div class="counter">-->
        <!--<h3>Estimated Time Remaining Before Launch:</h3>-->
<!---->
        <!--<div id="countdown">-->
        <!--</div>-->
      <!--</div>-->
<!---->
      <script type="text/javascript" charset="utf-8">
          // set the date we're counting down to
          var target_date = new Date('Jun, 15, 2015').getTime();

          // variables for time units
          var days, hours, minutes, seconds;

          // get tag element
          var countdown = document.getElementById('countdown');

          // update the tag with id "countdown" every 1 second
          setInterval(function () {

              // find the amount of "seconds" between now and target
              var current_date = new Date().getTime();
              var seconds_left = (target_date - current_date) / 1000;

              // do some time calculations
              days = parseInt(seconds_left / 86400);
              seconds_left = seconds_left % 86400;

              hours = parseInt(seconds_left / 3600);
              seconds_left = seconds_left % 3600;

              minutes = parseInt(seconds_left / 60);
              seconds = parseInt(seconds_left % 60);

              // format countdown string + set tag value
              countdown.innerHTML = '<span class="days">' + days + ' <b>Days</b></span> <span class="hours">' + hours + ' <b>Hours</b></span> <span class="minutes">'
                      + minutes + ' <b>Minutes</b></span> <span class="seconds">' + seconds + ' <b>Seconds</b></span>';

          }, 1000);
      </script>

      <!--<div class="welcome-footer">-->
      <!--<hr>-->
      <!--<p class='text-center' style="color: #fff;">Video Depot <a href="http://getbootstrap.com" style="color: gray;">Maksym Tymoshyk</a>. &copy;2015-->
      <!--</p>-->
      <!--</div>-->
    </div>
  </div>
</div>
</body>